/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvSUJNX0FETUlOL0RvY3VtZW50cy9Qcm9qZWN0cy9wZXJzb25hbC9DbG91ZFZlcmFuby9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0lCTV9BRE1JTi9Eb2N1bWVudHMvUHJvamVjdHMvcGVyc29uYWwvQ2xvdWRWZXJhbm8vc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
