/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.table[_ngcontent-%COMP%] {\r\n    border-radius: 5px;\r\n    width: 50%;\r\n    margin: auto;\r\n    float: none;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvSUJNX0FETUlOL0RvY3VtZW50cy9Qcm9qZWN0cy9wZXJzb25hbC9DbG91ZFZlcmFuby9zcmMvYXBwL2Rhc2hib2FyZC9kYXNoYm9hcmQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9JQk1fQURNSU4vRG9jdW1lbnRzL1Byb2plY3RzL3BlcnNvbmFsL0Nsb3VkVmVyYW5vL3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2hib2FyZC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
